/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Client_form: typeof import('./components/Client_form.vue')['default']
    Clientes: typeof import('./components/Clientes.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Home_p: typeof import('./components/Home_p.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Polizas: typeof import('./components/Polizas.vue')['default']
    Polizas_form: typeof import('./components/Polizas_form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
